# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d61422e2bcdbfcaae6af14903ca33a350138119177be7162fe54bf88253accc9d85e93f5475f874f5ad5da5a8396b82db661d2649c57aa795cf633ac039b7c9c

test:
  secret_key_base: 63f1a7ae97756c347e1010261a6fe9cca81500df73fad0031df114f293d25d356ea11eabe14d7e5785a8eb14c734fb1309af44e1631e81724c92be3b43c29e4e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
